language: julia
os:
  - osx
  - linux
julia:
  - 0.5
before_install:
  - sudo apt-get update -qq -y
  - sudo apt-get install libpcre3-dev julia -y
  - sudo apt-get install python-matplotlib
notifications:
  email: false
after_success:
  - julia -e 'cd(Pkg.dir("ApproXD")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';


