language: julia
os:
  - linux
julia:
  - 0.5
notifications:
  email: false
after_success:
  - julia -e 'cd(Pkg.dir("ApproXD")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';


